"use client";

import { CheckCircle2, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";
import Shell from "../../components/Shell";
import { SkeletonText } from "../../components/Skeleton";
import { api, IndexSummary, Route } from "../../lib/api";

const HORIZONS = [
  ["T+1", "1 day before departure", "Last-minute / spot fares"],
  ["T+7", "7 days before departure", "Short-lead travel"],
  ["T+15", "15 days before departure", "Mid-horizon booking"],
  ["T+30", "30 days before departure", "Planned / advance booking"],
  ["T+45", "45 days before departure", "Long-range booking"],
];

export default function Methodology() {
  const [routes, setRoutes] = useState<Route[]>([]);
  const [summary, setSummary] = useState<IndexSummary | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    Promise.all([api.getRoutes(), api.getIndex().catch(() => null)])
      .then(([r, s]) => {
        setRoutes(r);
        setSummary(s);
      })
      .finally(() => setLoading(false));
  }, []);

  const routeCount = routes.length;
  const weightPct = routes[0]?.weight ? (Number(routes[0].weight) * 100).toFixed(3) : null;

  return (
    <Shell active="methodology">
      <main className="method-page">
        <div className="method-ribbon">
          <span><ShieldCheck size={13} />INDEX METHODOLOGY</span>
          <span>Source code: app/index_engine/, app/cleaning/</span>
          <b>{loading ? "…" : `${routeCount} routes tracked`}</b>
        </div>
        <div className="method-content">
          <section className="method-title">
            <div>
              <span>HOW THE INDEX IS CALCULATED</span>
              <h1>Methodology</h1>
              <p>
                This page describes exactly what the backend computes — no invented formulas or
                fabricated figures. Every number below is generated by the same code that powers
                the rest of this dashboard.
              </p>
            </div>
          </section>

          <section className="card method-section executive">
            <header><b>01</b><h2>What the index measures</h2><span>OVERVIEW</span></header>
            <div className="executive-body">
              <div>
                <p>
                  The Airfare Price Index (APIx) tracks how much domestic flight prices have moved
                  relative to a starting point (the &quot;base period&quot;), for each tracked route and
                  for five separate booking-lead-time windows. An index value of 120 means fares are
                  20% higher than the base period; 90 means 10% lower.
                </p>
                <div className="mandate-stats">
                  <span><small>TRACKED ROUTES</small>{loading ? <SkeletonText className="sm" /> : <b>{routeCount}</b>}<p>Origin–destination pairs currently in the routes table.</p></span>
                  <span><small>ROUTE WEIGHT (equal-weight seed)</small>{loading ? <SkeletonText className="sm" /> : <b>{weightPct ? `${weightPct}%` : "—"}</b>}<p>Every route currently counts equally toward the overall index (1 ÷ route count).</p></span>
                  <span><small>CURRENT OVERALL INDEX</small>{loading ? <SkeletonText className="sm" /> : <b>{summary ? Number(summary.index).toFixed(2) : "—"}</b>}<p>Live value from GET /api/v1/index, base = 100.</p></span>
                </div>
              </div>
            </div>
          </section>

          <section className="card method-section">
            <header><b>02</b><h2>Data collection</h2><span>SCRAPING</span></header>
            <div className="ingestion-method">
              <article>
                <h3>Source</h3>
                <p>
                  Every fare comes from a live Google Flights search, scraped with Playwright
                  (a real, scriptable browser). We do not use any other airline site, OTA, or
                  third-party fare API.
                </p>
              </article>
              <article>
                <h3>Advance booking windows (T+N)</h3>
                <p>Each route is scraped separately for 5 fixed lead times — never read from Google&apos;s price calendar (we tested it; its prices don&apos;t match the real flight-card prices).</p>
                <div className="method-table">
                  <table>
                    <thead><tr><th>WINDOW</th><th>MEANING</th><th>TYPICAL USE CASE</th></tr></thead>
                    <tbody>
                      {HORIZONS.map((h) => (
                        <tr key={h[0]}>{h.map((x) => <td key={x}>{x}</td>)}</tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </article>
            </div>
          </section>

          <section className="card method-section">
            <header><b>03</b><h2>What counts as the price</h2><span>PRICE DEFINITION</span></header>
            <div className="price-protocol">
              <article>
                <h3>Used</h3>
                <p>✓ The total fare Google Flights displays for one adult, economy, one-way — this already includes taxes and mandatory fees, since that&apos;s what Google shows.</p>
              </article>
              <article>
                <h3>Not invented</h3>
                <p>× We do not attempt to split the total into base fare / taxes / UDF / convenience fee. Google Flights doesn&apos;t expose that breakdown, so those database columns are left empty rather than guessed.</p>
              </article>
            </div>
          </section>

          <section className="card method-section formulas">
            <header><b>04</b><h2>The actual math</h2><span>FORMULAS</span></header>
            <article>
              <div><small>STEP 1</small><h3>Representative fare per route + window</h3><p>For each (route, advance_days) group, take the median of the cleaned, non-outlier fares. Median is used instead of mean because fare distributions are skewed by a few expensive last-minute fares.</p></div>
              <strong>representative_fare = median(valid, non-outlier fares in that group)</strong>
            </article>
            <article>
              <div><small>STEP 2</small><h3>Route price relative</h3><p>The &quot;base&quot; fare is the representative fare from the earliest scrape we have for that route/window. The &quot;current&quot; fare is from the most recent scrape.</p></div>
              <strong>route_index = (current_fare / base_fare) × 100</strong>
            </article>
            <article>
              <div><small>STEP 3</small><h3>Overall index (weighted average)</h3><p>Only routes that have both a current fare, a base fare, and a weight are included. Weights are re-normalized across just those routes so they sum to 1.</p></div>
              <strong>overall_index = Σ (route_weight × route_index)</strong>
            </article>
          </section>

          <section className="card method-section">
            <header><b>05</b><h2>Data cleaning, before any of the above runs</h2><span>QUALITY CONTROL</span></header>
            <div className="quality-method">
              <article>
                <h3>Pipeline order</h3>
                <p>validate → normalize → deduplicate → flag outliers → save as a fare_observation. Raw scraped data (fare_quotes) is never edited or deleted — cleaning only decides what gets promoted.</p>
                <section>
                  <span><b>Validation</b><em>rule-based</em><p>Rejects a quote if it&apos;s missing a route, has a price ≤ 0, an unrecognized currency, no departure date, or an implausible duration/stop count.</p></span>
                  <span><b>Deduplication</b><em>exact match</em><p>Same route + airline + flight number + departure time + fare seen more than once → keep the earliest, drop the rest.</p></span>
                </section>
              </article>
              <article>
                <h3>Outlier detection: IQR (Tukey fence)</h3>
                <p>Within each (route, advance_days) group with at least 4 observations, a fare is flagged — not deleted — if it falls outside Q1 − 1.5×IQR to Q3 + 1.5×IQR. Flagged fares stay in the database with is_outlier = true, and the index calculation simply excludes them from the representative-fare median.</p>
              </article>
            </div>
          </section>

          <section className="card method-section governance">
            <header><b>06</b><h2>How this differs from the official CPI</h2><span>MoSPI COMPARISON</span></header>
            <div className="method-table">
              <table>
                <thead><tr><th>DIMENSION</th><th className="tone0">OFFICIAL CPI (MoSPI, 2024=100)</th><th className="tone3">APIx (this project)</th></tr></thead>
                <tbody>
                  <tr><td><b>Air fare data source</b></td><td>Manual price collection by field staff visiting ~1,181 rural + 1,114 urban centres/ticketing offices once a month</td><td>Live Google Flights scrape via Playwright, automated, repeatable on demand</td></tr>
                  <tr><td><b>Update frequency</b></td><td>Monthly — one snapshot price per item per centre</td><td>Continuous — every scrape run adds fresh observations</td></tr>
                  <tr><td><b>Publication lag</b></td><td>15–30 days between survey and release; published ~12th of the following month</td><td>Index recomputes immediately after each scrape completes</td></tr>
                  <tr><td><b>Booking lead time</b></td><td>Not captured — a single fare per item, no notion of how far in advance it was booked</td><td>5 explicit windows (T+1, T+7, T+15, T+30, T+45) per route, scraped separately</td></tr>
                  <tr><td><b>Route granularity</b></td><td>Air fare is one item inside the 8.59%-weight &quot;Transport &amp; Communication&quot; sub-group — not broken out by route</td><td>Per-route index for every tracked city pair, then weighted into a national index</td></tr>
                  <tr><td><b>Weighting basis</b></td><td>Fixed Laspeyres weights from the Household Consumption Expenditure Survey, unchanged until the next base-year revision (years apart)</td><td>Equal-weight seed per route today; designed to accept revised weights without a methodology change</td></tr>
                  <tr><td><b>Outlier handling</b></td><td>Not publicly documented at the item level</td><td>IQR (Tukey fence) flagging per route/window, raw data preserved, flagged fares excluded from the median only</td></tr>
                </tbody>
              </table>
            </div>
            <footer>
              <span>Sources: MoSPI CPI weight tables · MoSPI CPI FAQs (2024 series) · MoSPI CPI press releases</span>
              <b>Comparison compiled from public MoSPI documentation, Sept 2026</b>
            </footer>
          </section>

          <section className="card method-section executive">
            <header><b>07</b><h2>Why a route-and-window index closes a real gap</h2><span>WHY THIS APPROACH</span></header>
            <div className="executive-body">
              <div>
                <p>
                  Over 90% of domestic air tickets in India are now bought online, where prices move by
                  the hour with yield management, surge pricing, and seat scarcity. A monthly field visit
                  to a handful of ticketing offices cannot capture that — it records one fare, once a
                  month, with no way to say whether that fare was booked a day out or six weeks out.
                  Airfare is consistently flagged as one of the most volatile items in the CPI basket for
                  exactly this reason.
                </p>
                <p style={{ marginTop: "8px" }}>
                  APIx is built to sit alongside the official CPI as a high-frequency, route-level,
                  lead-time-aware signal for the same underlying item — not to replace the survey, but to
                  fill the gap a monthly manual snapshot structurally cannot close.
                </p>
              </div>
              <aside>
                <h3>In one line</h3>
                <p>CPI tells you air fares moved. APIx tells you which route, which booking window, and how much — every day.</p>
                <span>DESIGNED TO AUGMENT MoSPI CPI, NOT REPLACE IT</span>
              </aside>
            </div>
          </section>

          <section className="method-legal">
            <CheckCircle2 size={15} />
            <span>This is a working prototype, not an officially gazetted statistical release. The methodology above matches the current source code exactly — if the code changes, this page should be updated alongside it.</span>
          </section>
        </div>
      </main>
    </Shell>
  );
}
